apiVersion: v2
name: k8s-agent
description: PingReports Kubernetes monitoring agent
type: application
version: 0.1.2
appVersion: "0.1.2"
home: https://app-pr.sxp.dev
sources:
  - https://github.com/PingReports/k8s-agent
maintainers:
  - name: PingReports
    email: ops@stackxperts.com
